4차 PR - Naver 로그인
honeySleepr/JpaPlayground pull request #8
Opened 2022-10-10 11:58 UTC by honeySleepr

안녕하세요~~ 즐거운 주말 보내셨나요!
PR을 조금 더 빨리 보내보려했는데 정해진 기한이 없어서 그런지, 코쿼 미션 때에 비해 참 진도가 안나가는 느낌이네요.
바쁘신데 시간 내주셔서 감사합니다 🙇 

## 🛠️ 주요 구현 사항

- Naver OAuth 로그인 구현
- 다른 OAuth Server를 쉽게 추가 할 수 있도록 설계 변경
- Product 테스트 구조 변경 ( 이제 테스트 그만 손대고 구현에 힘을 쏟겠습니다 🥲 )
    - TestData 클래스에서 데이터 세팅 및 rollback
    - Repository 테스트 삭제

## ❓질문

1. (링크) `RestTemplate.postForObject()` 메서드에 Object request 인자로 DTO를 넘겼을 때와, MultiValueMap을 넘겼을 때 어떤 차이점이 있나요?  
GitHub 로그인을 할때는 DTO에 인자들을 담아서 `HttpEntity<GithubAccessTokenRequest> requestHttpEntity = new HttpEntity<>(new GithubAccessTokenRequest(code, properties), headers);` 형태로 요청을 보내서 성공적으로 응답을 받았는데,  Naver는 같은 방식으로 하니 401 응답이 와서 현재 DTO 대신 MultiValueMap을 body로 넣어주는 방식으로 구현한 상태입니다. 어떤 차이점 때문에 이 문제가 발생하는지 모르겠습니다ㅠㅠ

2. Nested JSON을 parsing 하기 위해 NaverOAuthProvider에 static inner class를 만들어 구현하였는데, NaverUserInfo dto 안에서 더 깔끔하게 처리할 수 있는 방법이 있을까요?
Naver 유저 정보 응답은 아래와 같은 형태입니다.
```json
{
  "resultcode": "00",
  "message": "success",
  "response": {
    "email": "openapi@naver.com",
    "nickname": "OpenAPI",
    "profile_image": "https://ssl.pstatic.net/static/pwe/address/nodata_33x33.gif",
    "age": "40-49",
    "gender": "F",
    "id": "32742776",
    "name": "오픈 API",
    "birthday": "10-01",
    "birthyear": "1900",
    "mobile": "010-0000-0000"
  }
}
```

2022-10-10 12:01 UTC, honeySleepr commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +	}
* Nested JSON을 parsing 하기 위해 NaverOAuthProvider에 static inner class를 만들어 구현하였는데, NaverUserInfo dto 안에서 더 깔끔하게 처리할 수 있는 방법이 있을까요?

Naver 유저 정보 응답은 아래와 같은 형태입니다.
```json
{
  "resultcode": "00",
  "message": "success",
  "response": {
    "email": "openapi@naver.com",
    "nickname": "OpenAPI",
    "profile_image": "https://ssl.pstatic.net/static/pwe/address/nodata_33x33.gif",
    "age": "40-49",
    "gender": "F",
    "id": "32742776",
    "name": "오픈 API",
    "birthday": "10-01",
    "birthyear": "1900",
    "mobile": "010-0000-0000"
  }
}
```

2022-10-10 14:35 UTC, naneun requested changes

2022-10-10 14:35 UTC, naneun commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
일단 GitHub OAuth 로그인 시에 `DTO 클래스` 나 `MultiValueMap` 을 사용하지 말고 `HashMap` 으로 파라미터 값을 넘겨보고 테스트해보면 이유를 알 수 있을 거 같네요.

2022-10-10 15:37 UTC, honeySleepr commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
HashMap 또는 DTO로 입력하였을 때는 `key-value` 형태로 바로 매핑되는데
MultiValueMap 으로 입력하는 경우 List 형태로 매핑되는군요! 그러면 아래와 같은 형식으로 JSON 응답이 보내지는게 맞나요..?
```json
{
    "code" : {
         "code" : "abcde123"
    }
    ...
}
```

그렇다면 GitHub는 JSON이 Nested 되어있든 아니든 모든 경우에 정상적으로 파싱 되도록 구현되어있어서 DTO든 MultivalueMap이든 모든 경우 다 성공적으로 인증이 되는 것이었고, 
Naver는 Nested 형태인 경우에만 정상적으로 파싱되도록 구현되어있는 차이인가요?? 🤔

* HashMap  
![image](https://user-images.githubusercontent.com/92678400/194901766-7e6eb8ef-d860-4ebe-8927-341ae4192ab3.png)
* MultiValueMap  
![image](https://user-images.githubusercontent.com/92678400/194902036-d7ccbf12-56b9-4d83-8d37-8007f924b6d6.png)

2022-10-10 16:48 UTC, naneun commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
```
{
    "code" : [ "abcde123" ]
    ...
}
```

이런 형식으로 봐야겠죠?

2022-10-10 16:54 UTC, naneun commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
>GitHub는 JSON이 Nested 되어있든 아니든 모든 경우에 정상적으로 파싱 되도록 구현되어있어서 DTO든 MultivalueMap이든 모든 경우 다 성공적으로 인증이 되는 것이었고,
Naver는 Nested 형태인 경우에만 정상적으로 파싱되도록 구현되어있는 차이인가요??

네 이전 프로젝트에서 구현했던 Google OAuth 로그인 기능에서도 DTO 클래스로 파라미터 값을 세팅해서 보내주어도 성공했던 거로 봐선 네이버 서버 측에는 MultiValueMap 형식으로 전달된 파라미터 값들만 파싱하도록 구현되어있는 것 같습니다.

2022-10-10 17:10 UTC, naneun commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
```java
public static MultiValueMap<String, String> convertToMultiValueMap(Object obj) {
    MultiValueMap<String, String> params = new LinkedMultiValueMap<>();
    params.setAll(objectMapper.convertValue(obj, new TypeReference<>() {}));

    return params;
}
```

예전에 스프링 카페 구현할 때 작성해놓고 사용했던 메서드인데 이 메서드를 사용하면 Naver 서버에 요청할 때 사용하던 Request DTO 클래스를 지우지 않고 활용할 수 있을 거에요.

objectMapper -> `ObjectMapper` 클래스 인스턴스

2022-10-11 04:31 UTC, honeySleepr commented on src/main/java/com/jpaplayground/domain/product/exception/ProductNotFoundException.java
> +public class ProductNotFoundException extends BusinessException {
NotFoundException을 공용으로 사용하되 ErrorCode를 상황에 맞게 쓰는 방식으로 바꿔보겠습니다!

2022-10-11 04:31 UTC, honeySleepr commented on src/main/java/com/jpaplayground/global/login/oauth/NaverOAuthProvider.java
> +		return restTemplate.postForObject(url, requestHttpEntity, OAuthAccessToken.class);
오오오 옵젝매퍼! 또 하나 배워갑니다 🤩👍👍

2022-10-11 08:58 UTC, naneun approved these changes

2022-10-14 03:37 UTC, merged